version: '2'
services:
  central-ledger:
    env_file: .env
    build: .
    ports:
     - "3000:3000"
    depends_on:
     - postgres
    networks:
     - back    
  postgres:
    env_file: .env
    image: postgres:9.3
    networks:
     - back
    volumes:
     - postgres-data:/var/lib/postgresql/data
networks:
  back: {}
volumes:
  postgres-data: {}